### ISSUE TITLE
error running "make instance-setup" step

### ISSUE THREAD

**Issue by antonpolishko** [mshytikov/cloudbook-pro#1]
Getting an error during "make instance-setup" step. Arrises due to conflict with existing git on the system

```
stow --dir=dotfiles --target ~ -v git
WARNING! stowing git would cause conflicts:
  * existing target is neither a link nor a directory: .gitconfig
All operations aborted.
make: *** [dotfiles-setup] Error 1
```

MacOS High Sierra 10.13.4 with git version 2.16.2 (homebrew)

**Comment by antonpolishko** [comment]
The error doesn't arise if you don't have ```~/.gitconfig``` file present

**Comment by mshytikov** [comment]
Fixed with auto backup of original files via git stash. #2
